### ISSUE TITLE
Add a dark mode toggle button 

### ISSUE THREAD

**Issue by Siddheshjondhale** [M17-Project/REPEATER#10]
![image](https://user-images.githubusercontent.com/84581657/196006696-b29cb771-0ec6-4e2d-bfc6-a2e1d707583f.png)

Like to add a dark mode in website 
Kindly let me know what you think about it and assign me this issue .

**Comment by tarxvftech** [comment]
Are you willing to add some more CSS and maybe UI elements, too? We don't have any styling (besides mvp.css) in the first place, so a dark mode is kinda overkill for now. :grin:

**Comment by tarxvftech** [comment]
Specifically, the goal is to have a very capable and user friendly searchable database of entries, allowing for text, tag, or license+band search, or geographic search on a map. Anything headed that direction is progress.

**Comment by Siddheshjondhale** [comment]
> Specifically, the goal is to have a very capable and user friendly searchable database of entries, allowing for text, tag, or license+band search, or geographic search on a map. Anything headed that direction is progress.

I can add a responsive navbar if you want using bootstrap

**Comment by Siddheshjondhale** [comment]
> > Specifically, the goal is to have a very capable and user friendly searchable database of entries, allowing for text, tag, or license+band search, or geographic search on a map. Anything headed that direction is progress.
> 
> I can add a responsive navbar if you want using bootstrap

Should i open this issue ?

**Comment by tarxvftech** [comment]
No thanks for now, the navbar is already responsive using MVP and is actually one of the few functional UI elements of the site.

Where you could help a ton is by getting the repeater list output in a responsive table-like view - something that will work with javascript disabled. Something functionally like https://automatic.sral.fi/ as an example.
