### ISSUE TITLE
Remote .json fetch and database import (medium)

### ISSUE THREAD

**Issue by tarxvftech** [M17-Project/REPEATER#4]
We have the (un?)enviable task of maintaining a database of multiple repeaters and other radio-related items. One of the hardest parts of managing these databases is keeping the data up-to-date. Since we're not the only database for this topic, we need a way to stand out as *easier to manage* than all the others. Repeaters are expensive, usually $5k-$10k of hardware and sometimes up to hundreds of dollars a month to run and maintain, so they are often managed by radio clubs, where the costs can be spread out in the form of club dues. 
This means there's often one person who actually knows all the details of all the repeaters in an area, and they will be overworked trying to updated all the repeater database sites. So they don't! What they usually do is just make sure their club website is up to date, and call it a day.

One possible way to have the best of both worlds might be to support a [/.well_known path](https://www.keycdn.com/support/well-known) on foreign webservers. This, combined with a common JSON schema, would allow owners and operators of repeaters to render a single file with the most up to date information on their repeaters (name, frequency, location like lat and lon, etc) and put it on their club website. Then, sites like REPEATER can just go fetch that file.

**Task:**
1. Implement a way to fetch a json file (probably using requests) 
2. and validate it against the database models (e.g. make sure it has required data like callsign)
3. This is a task that django should run periodically, like once a week. Make it so it does so. I recommend using something like django-q to help with this. Provide an example or script of adding this task to the queue so it runs periodically (which you'll want to do to test it anyway).

For now, the json data can look like a json dict with some metadata and an array of repeaters (I'll attach an example below). 
If each repeater validates as reasonable data (e.g. has a name and frequencies, no zeros for lat or lon), it should be saved to the DB, creating new repeaters or overwriting an existing repeater that matches (assume the repeater name won't change and that the name+owner will be unique).

Example JSON that would be fetched:
```json
{
"owner":"New Hampshire Sunapee Radio Club",
"repeaters": [
  {
  "name":"W2FBI", 
  "freq_in": "146.895", 
  "freq_out":"146.295", 
  "access_information":"PL 67", 
  "lat":43.064056, 
  "lon": -70.967822, 
  "antenna_alt_above_terrain":"20m"
  } 
]
}
```
(The name of a repeater is often its callsign.)
If you do this, feel free to provide django tests in your PR or a separate PR. Those would be VERY appreciated for this kind of work.

**Comment by tarxvftech** [comment]
A valid live target you may use for dev and testing is at https://m17.club/.well_known/repeaters.json

**Comment by lonewolf9277** [comment]
Hello may I work on this?

**Comment by tarxvftech** [comment]
Please do! :D

**Comment by tarxvftech** [comment]
Finished by @lonewolf9277, thank you! :D
